# Generated by Django 5.2.14 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_otp_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('sacked', 'Sacked'), ('resigned', 'Resigned'), ('pending', 'Pending')], default='pending', max_length=15),
        ),
    ]
