# Generated by Django 5.2.14 on 2026-05-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_alter_employee_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditLog',
            new_name='AuditLogNew',
        ),
        migrations.RenameModel(
            old_name='DownloadLog',
            new_name='DownloadLogNew',
        ),
        migrations.RenameModel(
            old_name='EmployeeRequestAttachment',
            new_name='EmployeeRequestAttachmentNew',
        ),
        migrations.RenameModel(
            old_name='EmployeeRequest',
            new_name='EmployeeRequestNew',
        ),
        migrations.AlterModelTable(
            name='auditlognew',
            table='audit_logs_new',
        ),
        migrations.AlterModelTable(
            name='downloadlognew',
            table='download_logs_new',
        ),
        migrations.AlterModelTable(
            name='employeerequestattachmentnew',
            table='employee_request_attachments_new',
        ),
        migrations.AlterModelTable(
            name='employeerequestnew',
            table='employee_requests_new',
        ),
    ]
